version: "3.9"

services:
  logjam:
    image: logjam
    container_name: "logjam"
    build: ./
    ports:
      - "0.0.0.0:8080:8090"
    network_mode: bridge
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          memory: 4096M
